"""
radiology_pipeline.py
---------------------
Production-grade automated radiology report generator using IDEFICS2-8B.

Use Case: Chest X-Ray → Structured Radiology Report

The pipeline mirrors how a radiologist works:
  Step 1. Assess image quality
  Step 2. Identify key anatomical regions
  Step 3. Note findings in each region
  Step 4. Form an overall impression
  Step 5. Make recommendations

Each step uses a separate targeted few-shot call to IDEFICS2, then
the outputs are assembled into a structured JSON + narrative report.

Clinical disclaimer: FOR RESEARCH / DEMO ONLY.
Not validated for clinical use. Requires FDA/CE clearance for deployment.
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

from loguru import logger
from PIL import Image

from .config import ModelConfig
from .model import FewShotExample, FlamingoInferencePipeline, InferenceResult


# ---------------------------------------------------------------------------
# Output schema
# ---------------------------------------------------------------------------

@dataclass
class AnatomicalFinding:
    """A single radiological finding at a specific anatomical location."""
    location: str          # e.g. "Right lower lobe"
    finding: str           # e.g. "Consolidation present"
    severity: str          # "normal" | "mild" | "moderate" | "severe"
    confidence: str        # "low" | "medium" | "high"


@dataclass
class RadiologyReport:
    """
    Structured radiology report output.

    Mirrors standard radiology report sections used in clinical practice:
    - Clinical Information
    - Technique
    - Findings (per anatomical region)
    - Impression
    - Recommendations
    """
    patient_id: str                      = "UNKNOWN"
    study_date: str                      = ""
    modality: str                        = "Chest X-Ray (PA/AP)"

    # Report sections
    image_quality: str                   = ""
    clinical_information: str            = ""
    technique: str                       = ""

    # Structured findings
    lung_fields: str                     = ""
    cardiac_silhouette: str              = ""
    mediastinum: str                     = ""
    pleural_spaces: str                  = ""
    bones_and_soft_tissue: str           = ""
    diaphragm: str                       = ""
    additional_findings: str             = ""

    # Parsed finding list
    anatomical_findings: List[AnatomicalFinding] = field(default_factory=list)

    # Summary
    impression: str                      = ""
    recommendations: str                 = ""

    # Metadata
    model_id: str                        = ""
    total_latency_ms: float              = 0.0
    total_generated_tokens: int          = 0
    report_confidence: str               = "medium"    # low | medium | high
    warnings: List[str]                  = field(default_factory=list)

    def to_dict(self) -> Dict:
        d = asdict(self)
        d["anatomical_findings"] = [asdict(f) for f in self.anatomical_findings]
        return d

    def to_narrative(self) -> str:
        """Render report as a human-readable narrative text block."""
        lines = [
            "=" * 70,
            "RADIOLOGY REPORT",
            "=" * 70,
            f"Patient ID : {self.patient_id}",
            f"Study Date : {self.study_date}",
            f"Modality   : {self.modality}",
            "",
            "CLINICAL INFORMATION",
            "-" * 40,
            self.clinical_information or "Not provided.",
            "",
            "TECHNIQUE",
            "-" * 40,
            self.technique or "Standard PA/AP chest radiograph.",
            "",
            "IMAGE QUALITY",
            "-" * 40,
            self.image_quality or "Adequate for interpretation.",
            "",
            "FINDINGS",
            "-" * 40,
            f"Lung Fields           : {self.lung_fields}",
            f"Cardiac Silhouette    : {self.cardiac_silhouette}",
            f"Mediastinum           : {self.mediastinum}",
            f"Pleural Spaces        : {self.pleural_spaces}",
            f"Bones & Soft Tissue   : {self.bones_and_soft_tissue}",
            f"Diaphragm             : {self.diaphragm}",
        ]
        if self.additional_findings:
            lines += ["", f"Additional Findings   : {self.additional_findings}"]
        lines += [
            "",
            "IMPRESSION",
            "-" * 40,
            self.impression or "See findings above.",
            "",
            "RECOMMENDATIONS",
            "-" * 40,
            self.recommendations or "Clinical correlation recommended.",
            "",
            "=" * 70,
            f"Generated by: {self.model_id}",
            f"Latency: {self.total_latency_ms:.0f}ms  |  "
            f"Tokens generated: {self.total_generated_tokens}",
            f"Confidence: {self.report_confidence.upper()}",
        ]
        if self.warnings:
            lines += ["", "⚠ WARNINGS:", *[f"  - {w}" for w in self.warnings]]
        lines.append("=" * 70)
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Few-shot example library
# These would normally be stored in data/few_shot_examples/ as real images.
# For demo purposes we use text-only answers; real deployment uses real images.
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an expert radiologist with 20 years of experience reading chest "
    "radiographs. Provide precise, clinically accurate, structured findings. "
    "Be concise but complete. Use standard radiology terminology. "
    "If a finding is normal, state it explicitly. "
    "Do NOT speculate beyond what is visible in the image. "
    "⚠ This is a research tool — all output requires physician review."
)

# Prefabricated few-shot answers (used when few-shot demo images are available)
FEW_SHOT_LUNG_ANSWERS = [
    (
        "Lung fields: Clear bilaterally. No consolidation, effusion, or "
        "pneumothorax. Lung volumes are normal. No hilar lymphadenopathy."
    ),
    (
        "Lung fields: Right lower lobe consolidation consistent with pneumonia. "
        "Left lung clear. No pleural effusion. Mildly increased bronchovascular markings."
    ),
]

FEW_SHOT_IMPRESSION_ANSWERS = [
    "Normal chest radiograph. No acute cardiopulmonary process identified.",
    (
        "1. Right lower lobe pneumonia. 2. No pleural effusion. "
        "3. Recommend clinical correlation and follow-up in 4-6 weeks."
    ),
]


# ---------------------------------------------------------------------------
# Pipeline class
# ---------------------------------------------------------------------------

class RadiologyReportPipeline:
    """
    End-to-end pipeline: chest X-ray image → structured radiology report.

    Architecture:
      - Uses IDEFICS2-8B (FlamingoInferencePipeline under the hood)
      - Multi-step inference: each section is a separate targeted call
      - Few-shot prompting for each section (Flamingo paradigm)
      - Post-processing to extract structured data from free-text
      - Quality gates: image quality check, completeness validation

    Parameters
    ----------
    config : ModelConfig
    few_shot_image_dir : Optional path to a directory of example X-ray images.
                         If None, zero-shot prompting is used.
    """

    SECTION_PROMPTS = {
        "image_quality": (
            "Assess the technical quality of this chest X-ray. "
            "Comment on: patient positioning (PA vs AP), rotation, "
            "inspiration (lung volumes), exposure (over/under), "
            "and any artifacts. Rate as: Excellent / Adequate / Limited / Non-diagnostic."
        ),
        "lung_fields": (
            "Describe the lung fields in this chest X-ray. "
            "Comment on: lung volumes, aeration, consolidation, infiltrates, "
            "nodules/masses, interstitial markings, and hilar regions. "
            "State 'clear' explicitly if normal."
        ),
        "cardiac_silhouette": (
            "Evaluate the cardiac silhouette in this chest X-ray. "
            "Comment on: heart size (cardiothoracic ratio), cardiac contour, "
            "and any evidence of cardiomegaly or abnormal shape."
        ),
        "mediastinum": (
            "Describe the mediastinum in this chest X-ray. "
            "Comment on: mediastinal width, tracheal position, "
            "aortic knob, and any mediastinal masses or widening."
        ),
        "pleural_spaces": (
            "Evaluate the pleural spaces in this chest X-ray. "
            "Comment on: pleural effusions (right/left/bilateral, size), "
            "pneumothorax, and pleural thickening."
        ),
        "bones_and_soft_tissue": (
            "Examine the bones and soft tissues visible in this chest X-ray. "
            "Comment on: ribs (fractures, lesions), clavicles, scapulae, "
            "vertebrae, and soft tissue abnormalities."
        ),
        "impression": (
            "Based on this chest X-ray, provide a concise radiology impression. "
            "List the top 1-3 findings in order of clinical importance. "
            "Format as a numbered list."
        ),
        "recommendations": (
            "Based on the findings in this chest X-ray, what clinical recommendations "
            "would you make? Consider: follow-up imaging, clinical correlation, "
            "urgent vs routine action."
        ),
    }

    def __init__(
        self,
        config: ModelConfig,
        few_shot_image_dir: Optional[Path] = None,
    ):
        self.config = config
        self.few_shot_dir = few_shot_image_dir
        logger.info("Initializing RadiologyReportPipeline...")
        self.pipeline = FlamingoInferencePipeline(config)
        self._few_shot_cache: Dict[str, List[FewShotExample]] = {}
        logger.info("Pipeline ready.")

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def generate_report(
        self,
        image_path: Union[str, Path, Image.Image],
        patient_id: str = "UNKNOWN",
        study_date: str = "",
        clinical_info: str = "",
        modality: str = "Chest X-Ray",
        run_all_sections: bool = True,
        sections: Optional[List[str]] = None,
    ) -> RadiologyReport:
        """
        Generate a full structured radiology report from a chest X-ray.

        Parameters
        ----------
        image_path : Path/URL/PIL image of the chest X-ray.
        patient_id : Patient identifier for the report header.
        study_date : Date of the study (YYYY-MM-DD).
        clinical_info : Clinical indication / history provided by the clinician.
        modality : Imaging modality string.
        run_all_sections : If True, run all 8 sections. If False, use `sections`.
        sections : List of section keys to run (subset of SECTION_PROMPTS).

        Returns
        -------
        RadiologyReport
        """
        t0 = time.perf_counter()
        logger.info(f"Generating report for patient={patient_id}, image={image_path}")

        report = RadiologyReport(
            patient_id=patient_id,
            study_date=study_date,
            modality=modality,
            clinical_information=clinical_info,
            model_id=self.config.model_id,
        )

        # Determine which sections to run
        section_keys = list(self.SECTION_PROMPTS.keys()) if run_all_sections else (sections or [])

        # Run each section
        total_tokens = 0
        for section_key in section_keys:
            logger.info(f"  → Section: {section_key}")
            result = self._run_section(image_path, section_key, clinical_info)
            total_tokens += result.generated_tokens
            self._apply_section_result(report, section_key, result.text)

        # Post-processing
        report.anatomical_findings = self._extract_structured_findings(report)
        report.report_confidence = self._assess_confidence(report)
        report.warnings = self._quality_gates(report)
        report.total_latency_ms = (time.perf_counter() - t0) * 1000
        report.total_generated_tokens = total_tokens

        logger.info(
            f"Report complete. Total latency: {report.total_latency_ms:.0f}ms, "
            f"Tokens: {total_tokens}, Confidence: {report.report_confidence}"
        )
        return report

    # ------------------------------------------------------------------
    # Section runner
    # ------------------------------------------------------------------

    def _run_section(
        self,
        image_path: Union[str, Path, Image.Image],
        section_key: str,
        clinical_info: str,
    ) -> InferenceResult:
        """Run one section of the report with few-shot prompting."""
        prompt = self.SECTION_PROMPTS[section_key]
        if clinical_info:
            prompt = f"[Clinical context: {clinical_info}]\n\n{prompt}"

        few_shot = self._get_few_shot_examples(section_key)

        return self.pipeline.generate(
            image_path=image_path,
            prompt=prompt,
            few_shot_examples=few_shot,
            system_context=SYSTEM_PROMPT,
            enhance_contrast=True,   # Always apply CLAHE for X-rays
        )

    # ------------------------------------------------------------------
    # Few-shot example management
    # ------------------------------------------------------------------

    def _get_few_shot_examples(self, section_key: str) -> List[FewShotExample]:
        """
        Return few-shot examples for the given section.
        In production: loads real X-ray images from self.few_shot_dir.
        In demo mode (no dir): returns empty list (zero-shot).
        """
        if section_key in self._few_shot_cache:
            return self._few_shot_cache[section_key]

        examples: List[FewShotExample] = []

        if self.few_shot_dir and self.few_shot_dir.exists():
            section_dir = self.few_shot_dir / section_key
            if section_dir.exists():
                for img_path in sorted(section_dir.glob("*.jpg"))[:2]:  # Max 2-shot
                    answer_path = img_path.with_suffix(".txt")
                    if answer_path.exists():
                        answer = answer_path.read_text().strip()
                        examples.append(FewShotExample(
                            image_source=img_path,
                            prompt=self.SECTION_PROMPTS[section_key],
                            answer=answer,
                        ))
                logger.debug(f"Loaded {len(examples)} few-shot examples for '{section_key}'")
            else:
                logger.debug(f"No few-shot dir for '{section_key}' — using zero-shot.")
        else:
            logger.debug("No few-shot image dir configured — zero-shot inference.")

        self._few_shot_cache[section_key] = examples
        return examples

    # ------------------------------------------------------------------
    # Applying results to report
    # ------------------------------------------------------------------

    def _apply_section_result(
        self, report: RadiologyReport, section_key: str, text: str
    ) -> None:
        """Map the model's free-text output to the correct RadiologyReport field."""
        text = text.strip()
        mapping = {
            "image_quality": "image_quality",
            "lung_fields": "lung_fields",
            "cardiac_silhouette": "cardiac_silhouette",
            "mediastinum": "mediastinum",
            "pleural_spaces": "pleural_spaces",
            "bones_and_soft_tissue": "bones_and_soft_tissue",
            "impression": "impression",
            "recommendations": "recommendations",
        }
        attr = mapping.get(section_key)
        if attr:
            setattr(report, attr, text)

    # ------------------------------------------------------------------
    # Post-processing
    # ------------------------------------------------------------------

    def _extract_structured_findings(
        self, report: RadiologyReport
    ) -> List[AnatomicalFinding]:
        """
        Parse free-text findings into structured AnatomicalFinding objects.
        Uses simple rule-based NLP (in production: fine-tuned NER model).
        """
        findings = []
        severity_keywords = {
            "severe": ["massive", "severe", "critical", "large", "complete"],
            "moderate": ["moderate", "moderate-sized", "significant"],
            "mild": ["mild", "minimal", "small", "subtle", "trace"],
            "normal": ["clear", "normal", "unremarkable", "no evidence", "within normal"],
        }

        section_map = {
            "right lung": report.lung_fields,
            "left lung": report.lung_fields,
            "cardiac": report.cardiac_silhouette,
            "mediastinum": report.mediastinum,
            "pleural": report.pleural_spaces,
            "ribs/bones": report.bones_and_soft_tissue,
            "diaphragm": report.diaphragm,
        }

        for location, text in section_map.items():
            if not text:
                continue
            severity = "normal"
            text_lower = text.lower()
            for sev, keywords in severity_keywords.items():
                if any(kw in text_lower for kw in keywords):
                    severity = sev
                    break

            # Confidence from severity (heuristic)
            confidence_map = {"normal": "high", "mild": "medium", "moderate": "medium", "severe": "high"}

            findings.append(AnatomicalFinding(
                location=location.title(),
                finding=text[:200],   # Truncate for structured field
                severity=severity,
                confidence=confidence_map.get(severity, "medium"),
            ))

        return findings

    def _assess_confidence(self, report: RadiologyReport) -> str:
        """
        Heuristic confidence assessment based on report completeness.
        In production: calibrated probability from an ensemble.
        """
        filled_sections = sum([
            bool(report.lung_fields),
            bool(report.cardiac_silhouette),
            bool(report.mediastinum),
            bool(report.pleural_spaces),
            bool(report.impression),
        ])
        if filled_sections >= 4:
            return "high"
        elif filled_sections >= 2:
            return "medium"
        return "low"

    def _quality_gates(self, report: RadiologyReport) -> List[str]:
        """
        Run quality checks and return a list of warning strings.
        Failures here should trigger human review before clinical use.
        """
        warnings = []

        # Research disclaimer — always present
        warnings.append(
            "RESEARCH TOOL ONLY: Not validated for clinical use. "
            "All findings must be reviewed and confirmed by a licensed radiologist."
        )

        if "non-diagnostic" in (report.image_quality or "").lower():
            warnings.append("Image quality rated non-diagnostic — findings unreliable.")

        if not report.impression:
            warnings.append("Impression section is empty — report incomplete.")

        if report.report_confidence == "low":
            warnings.append("Low confidence report — likely insufficient image quality or model uncertainty.")

        if len(report.lung_fields) < 20:
            warnings.append("Lung fields description unusually short — may be incomplete.")

        return warnings

    # ------------------------------------------------------------------
    # Resource management
    # ------------------------------------------------------------------

    def __enter__(self) -> "RadiologyReportPipeline":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.pipeline.__exit__(exc_type, exc_val, exc_tb)

    def save_report(
        self,
        report: RadiologyReport,
        output_dir: Path,
        patient_id: str,
    ) -> Tuple[Path, Path]:
        """
        Save report as both JSON and plain-text narrative.

        Returns
        -------
        Tuple[json_path, txt_path]
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        safe_id = re.sub(r"[^\w\-]", "_", patient_id)

        json_path = output_dir / f"{safe_id}_report.json"
        txt_path = output_dir / f"{safe_id}_report.txt"

        with open(json_path, "w") as f:
            json.dump(report.to_dict(), f, indent=2)

        with open(txt_path, "w") as f:
            f.write(report.to_narrative())

        logger.info(f"Report saved: {json_path}, {txt_path}")
        return json_path, txt_path
